version: 2.1
jobs:
  build:
    docker:
      # Primary container image where all steps run
      - image: cimg/node:20.5.0
    steps: 
      - checkout
      - run: node --version
      - run:
        command: yarn
        name: Install Dependencies
      - run:
        command: yarn test
        name: Run Tests