version: 2.1
jobs:
  build:
    docker:
      # Primary container image where all steps run
      - image: cimg/base:2022.05
    steps: 
      - checkout
      - run: 
          name: "Say Hello"
          command: "echo Navtej" 