version: 2.1
jobs:
  build:
    docker:
      # Primary container image where all steps run
      - image: cimg/node:20.5.0
    steps: 
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app